version: '3'

services: 
  app:
    build: .
    container_name: background-node
    ports:
      - '3333:3333'
    depends_on: 
      - redis

  redis:
    image: redis:alpine
    container_name: background-redis
    ports: 
      - '6379:6379'
    volumes:
      - redis_data:/usr/lib/redis

volumes: 
  redis_data: